#!/bin/bash -l

#SBATCH -A g2019003
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 15:00:00
#SBATCH -J assembly_run
#SBATCH --mail-type=ALL
#SBATCH --mail-user g_nikiforos@hotmail.com

module load bioinfo-tools
module load megahit


megahit --kmin-1pass -t 8 -1 SRR4342129_1.paired.trimmed.fastq.gz,SRR4342133_1.paired.trimmed.fastq.gz\
 -2 SRR4342129_2.paired.trimmed.fastq.gz,SRR4342133_1.paired.trimmed.fastq.gz\
 -o /home/georg/genome_analysis/analyses/assembly_megahit_results/results
