#!/bin/bash -l

#SBATCH -A g2019003
#SBATCH -p core
#SBATCH -n 5
#SBATCH -t 04:00:00
#SBATCH -J checkm_run
#SBATCH --mail-type=ALL
#SBATCH --mail-user g_nikiforos@hotmail.com

module load bioinfo-tools
module load CheckM/1.0.12

checkm lineage_wf -t 5 -x fa --reduced_tree /home/georg/genome_analysis/analyses/bining_metabat_results/results\
 /home/georg/genome_analysis/analyses/bining_evaluation_checkm_results/results

