#!/bin/bash -l

#SBATCH -A g2019003
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 15:00:00
#SBATCH -J assembly_run
#SBATCH --mail-type=ALL
#SBATCH --mail-user g_nikiforos@hotmail.com

module load bioinfo-tools
module load MetaBat/2.12.1

metabat2 -i assembly_contigs -o /home/georg/genome_analysis/analyses/biniing_metabat_result/bins t 2
