#!/bin/bash -l

#SBATCH -A g2019003
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 08:00:00
#SBATCH -J phylophlan_run
#SBATCH --mail-type=ALL
#SBATCH --mail-user g_nikiforos@hotmail.com

# Load modules
module load bioinfo-tools
module load python
module load biopython
module load FastTree
module load muscle
module load usearch/5.2.32
module load phylophlan

cd /home/georg/genome_analysis/analyses/phylogeny_phylophlan_results/nsegata-phylophlan-1d174e34b2ae
phylophlan.py -t --nproc 4 -i metagenome

