#!/bin/bash -l

#SBATCH -A g2019003
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 05:00:00
#SBATCH -J prokka_run
#SBATCH --mail-type=ALL
#SBATCH --mail-user g_nikiforos@hotmail.com

module load bioinfo-tools
module load prokka/1.12-12547ca

prokka bin_9.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_9
prokka bin_22.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_22
prokka bin_3.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_3
prokka bin_5.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_5
prokka bin_23.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_23
prokka bin_29.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_29
prokka bin_4.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_4
prokka bin_12.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_12
prokka bin_21.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_21
prokka bin_35.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_35
prokka bin_26.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_26
prokka bin_25.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_25
prokka bin_6.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_6
prokka bin_14.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_14
prokka bin_30.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_30
prokka bin_13.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_13
prokka bin_16.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_16
prokka bin_20.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_20
prokka bin_2.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_2
prokka bin_38.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_38
prokka bin_34.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_34
prokka bin_31.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_31
prokka bin_39.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_39
prokka bin_7.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_7
prokka bin_36.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_36
prokka bin_8.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_8
prokka bin_15.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_15
prokka bin_17.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_17
prokka bin_1.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_1
prokka bin_24.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_24
prokka bin_11.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_11
prokka bin_28.fa --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/bacteria/bin_28

prokka bin_37.fa --kingdom Archaea --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/archaea/bin_37
prokka bin_19.fa --kingdom Archaea --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/archaea/bin_19
prokka bin_33.fa --kingdom Archaea --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/archaea/bin_33
prokka bin_18.fa --kingdom Archaea --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/archaea/bin_18
prokka bin_32.fa --kingdom Archaea --outdir /home/georg/genome_analysis/analyses/annotation_prokka_results/results/archaea/bin_32


